title: Digital Scout
description: Skills to thrive in the digital world.
url: "https://asokolsky.github.io"
baseurl: "/digital-scout"
theme: minima
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
header_pages:
  - Business/index.md
  - Career/index.md
  - Collaboration/index.md
  - Computing/index.md
  - Cryptography/index.md
  - Electronics/index.md
  - Fitness/index.md
  - Internet/index.md
  - Physics/index.md
exclude:
  - AGENTS.md
